CREATE DATABASE QuanLyDongHo
GO

USE QuanLyDongHo
go


/* SANPHAM */
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SANPHAM](
	MASP INT IDENTITY(1,1) NOT NULL,
	TENSP NVARCHAR (50) NULL,
	GIATIEN DECIMAL(18,0) NULL,
	MOTA NTEXT NULL,
	LOAIDAY NTEXT NULL,
	ANHBIA NVARCHAR (10) NULL,
	MAHANG INT NULL ,
	MATH INT NULL ,
 CONSTRAINT PK_SANPHAM PRIMARY KEY CLUSTERED 
(
	[MASP] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
DROP TABLE HANGSANXUAT
/* Hãng sản xuất */
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HANGSANXUAT](
	MAHANG INT IDENTITY(1,1) NOT NULL,
	TENHANG NCHAR(10) NULL,
 CONSTRAINT PK_HANGSANXUAT PRIMARY KEY CLUSTERED 
(
	[MAHANG] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

/* Thương Hiệu */
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[THUONGHIEU](
	MATH INT IDENTITY(1,1) NOT NULL,
	TENTH NCHAR(10) NULL,
 CONSTRAINT PK_THUONGHIEU PRIMARY KEY CLUSTERED 
(
	[MATH] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

/* Chi tiết đơn hàng */

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CHITIETDONHANG](
	MADON INT NOT NULL,
	MASP INT NOT NULL,
	SOLUONG INT NULL,
	DONGIA DECIMAL(18,0) NULL,
 CONSTRAINT PK_CHITIETDONHANG PRIMARY KEY CLUSTERED 
(
	[MADON] ASC,
	[MASP] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

/* Đơn hàng */
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DONHANG](
	MADON INT NOT NULL,
	NGAYDAT DATETIME NULL,
	TINHTRANG INT NULL,
	MAND INT NULL,
 CONSTRAINT PH_DONHANG PRIMARY KEY CLUSTERED 
(
	[MADON] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

/* Người dùng */
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NGUOIDUNG](
	MAND INT IDENTITY (1,1) NOT NULL,
	HOTEN NVARCHAR (50) NULL,
	EMAIL NVARCHAR(50) NULL,
	DIENTHOAI NCHAR(10) NULL,
	MATKHAU VARCHAR (50) NULL,
	IDQUYEN INT NULL,
	DIACHI NVARCHAR (100) NULL,
 CONSTRAINT PK_KHACHHANG PRIMARY KEY CLUSTERED 
(
	[MAND] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

/* Phan quyen */
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PHANQUYEN](
	IDQUYEN INT IDENTITY(1,1) NOT NULL,
	TENQUYEN NVARCHAR(20) NULL,
 CONSTRAINT PK_PHANQUYEN PRIMARY KEY CLUSTERED 
(
	[IDQUYEN] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
ALTER TABLE [dbo].[NGUOIDUNG] ADD  CONSTRAINT DF_NGUOIDUNG_IDQUYEN  DEFAULT ((0)) FOR [IDQUYEN]
GO
ALTER TABLE [dbo].[CHITIETDONHANG]  WITH CHECK ADD  CONSTRAINT FK_CHITIETDONHANG_DONHANG FOREIGN KEY([MADON])
REFERENCES [dbo].[DONHANG] ([MADON])
GO
ALTER TABLE [dbo].[CHITIETDONHANG] CHECK CONSTRAINT FK_CHITIETDONHANG_DONHANG
GO
ALTER TABLE [dbo].[CHITIETDONHANG]  WITH CHECK ADD  CONSTRAINT FK_CHITIETDONHANG_SANPHAM FOREIGN KEY([MASP])
REFERENCES [dbo].[SANPHAM] ([MASP])
GO
ALTER TABLE [dbo].[CHITIETDONHANG] CHECK CONSTRAINT FK_CHITIETDONHANG_SANPHAM
GO
ALTER TABLE [dbo].[DONHANG]  WITH CHECK ADD  CONSTRAINT FK_DONHANG_KHACHHANG FOREIGN KEY([MAND])
REFERENCES [dbo].[NGUOIDUNG] ([MAND])
GO
ALTER TABLE [dbo].[DONHANG] CHECK CONSTRAINT  FK_DONHANG_KHACHHANG
GO
ALTER TABLE [dbo].[NGUOIDUNG]  WITH CHECK ADD  CONSTRAINT FK_NGUOIDUNG_NGUOIDUNG FOREIGN KEY([IDQUYEN])
REFERENCES [dbo].[PHANQUYEN] ([IDQUYEN])
GO
ALTER TABLE [dbo].[NGUOIDUNG] CHECK CONSTRAINT FK_NGUOIDUNG_NGUOIDUNG
GO
ALTER TABLE [dbo].[SANPHAM]  WITH CHECK ADD  CONSTRAINT FK_SANPHAM_HANGSANXUAT FOREIGN KEY([MAHANG])
REFERENCES [dbo].[HANGSANXUAT] ([MAHANG])
GO
ALTER TABLE [dbo].[SANPHAM] CHECK CONSTRAINT FK_SANPHAM_HANGSANXUAT
GO
ALTER TABLE [dbo].[SANPHAM]  WITH CHECK ADD  CONSTRAINT FK_SANPHAM_THUONGHIEU FOREIGN KEY([MATH])
REFERENCES [dbo].[THUONGHIEU] ([MATH])
GO
ALTER TABLE [dbo].[SANPHAM] CHECK CONSTRAINT FK_SANPHAM_THUONGHIEU
GO
USE [master]
GO
ALTER DATABASE QuanLyDongHo SET  READ_WRITE 
GO

/* ---- */
GO
ALTER DATABASE QuanLyDongHo SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE QuanLyDongHo SET ANSI_NULLS OFF 
GO
ALTER DATABASE QuanLyDongHo SET ANSI_PADDING OFF 
GO
ALTER DATABASE QuanLyDongHo SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE QuanLyDongHo SET ARITHABORT OFF 
GO
ALTER DATABASE QuanLyDongHo SET AUTO_CLOSE ON 
GO
ALTER DATABASE QuanLyDongHo SET AUTO_SHRINK OFF 
GO
ALTER DATABASE QuanLyDongHo SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE QuanLyDongHo SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE QuanLyDongHo SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE QuanLyDongHo SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE QuanLyDongHo SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE QuanLyDongHo SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE QuanLyDongHo SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE QuanLyDongHo SET  DISABLE_BROKER 
GO
ALTER DATABASE QuanLyDongHo SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE QuanLyDongHo SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE QuanLyDongHo SET TRUSTWORTHY OFF 
GO
ALTER DATABASE QuanLyDongHo SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE QuanLyDongHo SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE QuanLyDongHo SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE QuanLyDongHo SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE QuanLyDongHo SET RECOVERY SIMPLE 
GO
ALTER DATABASE QuanLyDongHo SET  MULTI_USER 
GO
ALTER DATABASE QuanLyDongHo SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE QuanLyDongHo SET DB_CHAINING OFF 
GO
ALTER DATABASE QuanLyDongHo SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE QuanLyDongHo SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE QuanLyDongHo SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE QuanLyDongHo SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE QuanLyDongHo SET QUERY_STORE = OFF
GO
USE QuanLyDongHo
GO